#This file contains compiling message translation entries.
[Warning]
[警告]
[Error]
[錯誤]
[Hint]
[提示]
[Note]
[注解]
[Info]
[資訊]
invalid preprocessing directive
非法的預處理指令
extra tokens at end of #include directive
在 #include 指令末尾有多餘的符號
is defined in header
是定義於頭檔
did you forget to
你是否忘記要
did you mean
你是否想要
does not name a type
未命名某個類型
suggested alternative:
建議替換為:
No such file or directory
沒有這個檔或目錄
In function
在此函數中：
was not declared in this scope
未在此範圍內聲明
declared here
被聲明於此處
a function-definition is not allowed here before
函數定義不允許在此之前:
lvalue required as left operand of assignment
需要左值作為賦值左運算元
return-statement with a value, in function returning 'void'
在返回 'void' 的函數中，返回語句帶有一個值
integer overflow in expression of type 'int' results in
類型為'int'的運算式中出現整數溢出，導致結果為
no match for
不匹配
to match this
需要匹配這個
narrowing conversion of
變窄的轉換：
invalid conversion from
非法的轉換：從
no known conversion
沒有已知的轉換方法
in assignment
在賦值中
invalid operands of
無效的操作符:
In file included
在被包含的檔中
In member function
在成員函數中
request for member 
需要成員
which is of pointer type 
它是指針類型
maybe you meant to use 
也許你想要使用
recipe for target
配方對於目標
candidate:
候選:
undeclared (first use in this function)
未聲明（首次在此函數中使用）
each undeclared identifier is reported only once for each function it appears in,
出現在每個函數中的每個未聲明的識別字僅報告一次
At global scope:
在全局範圍內：
with no linkage
沒有關聯
previous declaration of
原先的聲明
was here
是在這裏
expected declaration specifiers
期待聲明說明符
declaration for parameter
聲明了參數
but no such parameter
但是沒有這個參數
redefinition of
重複定義：
has no member named
沒有成員
has not been declared
沒有被聲明
return type
返回的類型
is incomplete
是不完整的
aggregate
聚集體 
has incomplete type
的類型不完整
and cannot be defined
，無法被定義
which is of non-class type
它是非類(non-class)的類型
undefined reference to `WinMain'
程式中缺少 main 函數 
undefined reference to `WinMain@16'
程式中缺少 main 函數
ld returned 1 exit status
連接器返回錯誤代碼 1
assignment of read-only parameter
賦值給只讀參數
control reaches end of non-void function
控制到達非void函數的末尾
Cannot open output file
無法打開輸出檔
cannot open output file
無法打開輸出檔
Permission denied
讀寫許可權被拒絕
compilation terminated.
編譯異常中止
return-statement with no value, in function returning
return 運算式缺少值，而該函數要求返回值為
no return statement in function returning non-void
函數返回值類型並非 void，但缺少 return 語句
a function-definition is not allowed here before { token,
此處不允許在“{”標記之前使用函數定義
undefined reference to
未定義的引用：
storage size of
存儲大小
isn't known
未知
size of array 
數組 
is not an integral constant-expression
的大小不是一個整型常量運算式
invalid types
非法的類型
cannot convert
無法轉換
could not convert
無法轉換
for array subscript
對於數組下標
assignment of read-only variable
賦值給只讀變數
array bound is not an integer constant
數組邊界不是一個整型常量
array must be initialized with a brace-enclosed initializer
數組必須用大括弧括起的初始值設定初始化
forbids converting a string constant to 'char*' 
禁止轉換字串常量到字元指針
cannot be used as a function
不能作為函數使用
initializing argument
初始化參數
invokes undefined behavior
會引起未定義的行為
within this loop
在這個迴圈內
on array function parameter
對於函數參數
will return size of
將返回的大小是
is not a 
不是一個 
namespace-name
名字空間的名稱
redeclaration of
重複定義：
redeclared as different kind of entity
被重新聲明為不同類型的實體
previously defined here
原先已在此處定義
previously declared here
原先已在此處聲明
invalid use of incomplete type
非法地使用不完整的類型
forward declaration of 
前置聲明
request for
要求
which is of pointer type
但它是指針類型
maybe you meant to use
也許你想要使用
stray
非法字元
in program
在程式中
at end of input
在輸入檔的末尾
missing terminating
缺失終止的 
expected
期待
expects
期待
initializer
初始化
unqualified-id
非限定標識
primary-expression
基本運算式
declaration
聲明
identifier
識別字
token
符號
nested-name-specifier
嵌套名字說明符
before
在此之前:
failed
失敗
constructor
構造函數
destructor
析構函數
type conversion
類型轉換
operand
運算元
iteration
迭代
character
字元
operator
運算符
Information
資訊
argument
參數
file
檔
function
函數
member
成員
forget
忘記
forward
前置
for
對於
from
從
 and 
 和 
 to 
 到 
 or 
 或 
