#This file contains compiling message translation entries.
[Warning]
[警告]
[Error]
[错误]
[Hint]
[提示]
[Note]
[注解]
[Info]
[信息]
invalid preprocessing directive
非法的预处理指令
extra tokens at end of #include directive
在 #include 指令末尾有多余的符号
is defined in header
是定义于头文件
did you forget to
你是否忘记要
did you mean
你是否想要
does not name a type
未命名某个类型
suggested alternative:
建议替换为:
No such file or directory
没有这个文件或目录
In function
在此函数中：
was not declared in this scope
未在此范围内声明
declared here
被声明于此处
a function-definition is not allowed here before
函数定义不允许在此之前:
lvalue required as left operand of assignment
需要左值作为赋值左操作数
return-statement with a value, in function returning 'void'
在返回 'void' 的函数中，返回语句带有一个值
integer overflow in expression of type 'int' results in
类型为'int'的表达式中出现整数溢出，导致结果为
no match for
不匹配
to match this
需要匹配这个
narrowing conversion of
变窄的转换：
invalid conversion from
非法的转换：从
no known conversion
没有已知的转换方法
in assignment
在赋值中
invalid operands of
无效的操作符:
In file included
在被包含的文件中
In member function
在成员函数中
request for member 
需要成员
which is of pointer type 
它是指针类型
maybe you meant to use 
也许你想要使用
recipe for target
配方对于目标
candidate:
候选:
undeclared (first use in this function)
未声明（首次在此函数中使用）
each undeclared identifier is reported only once for each function it appears in,
出现在每个函数中的每个未声明的标识符仅报告一次
At global scope:
在全局范围内：
with no linkage
没有关联
previous declaration of
原先的声明
was here
是在这里
expected declaration specifiers
期待声明说明符
declaration for parameter
声明了参数
but no such parameter
但是没有这个参数
redefinition of
重复定义：
has no member named
没有成员
has not been declared
没有被声明
return type
返回的类型
is incomplete
是不完整的
aggregate
聚集体 
has incomplete type
的类型不完整
and cannot be defined
，无法被定义
which is of non-class type
它是非类(non-class)的类型
undefined reference to `WinMain'
程序中缺少 main 函数 
undefined reference to `WinMain@16'
程序中缺少 main 函数
ld returned 1 exit status
连接器返回错误代码 1
assignment of read-only parameter
赋值给只读参数
control reaches end of non-void function
控制到达非void函数的末尾
Cannot open output file
无法打开输出文件
cannot open output file
无法打开输出文件
Permission denied
读写权限被拒绝
compilation terminated.
编译异常中止
return-statement with no value, in function returning
return 表达式缺少值，而该函数要求返回值为
no return statement in function returning non-void
函数返回值类型并非 void，但缺少 return 语句
a function-definition is not allowed here before { token,
此处不允许在“{”标记之前使用函数定义
undefined reference to
未定义的引用：
storage size of
存储大小
isn't known
未知
size of array 
数组 
is not an integral constant-expression
的大小不是一个整型常量表达式
invalid types
非法的类型
cannot convert
无法转换
could not convert
无法转换
for array subscript
对于数组下标
assignment of read-only variable
赋值给只读变量
array bound is not an integer constant
数组边界不是一个整型常量
array must be initialized with a brace-enclosed initializer
数组必须用大括号括起的初始值设定初始化
forbids converting a string constant to 'char*' 
禁止转换字符串常量到字符指针
cannot be used as a function
不能作为函数使用
initializing argument
初始化参数
invokes undefined behavior
会引起未定义的行为
within this loop
在这个循环内
on array function parameter
对于函数参数
will return size of
将返回的大小是
is not a 
不是一个 
namespace-name
名字空间的名称
redeclaration of
重复定义：
redeclared as different kind of entity
被重新声明为不同类型的实体
previously defined here
原先已在此处定义
previously declared here
原先已在此处声明
invalid use of incomplete type
非法地使用不完整的类型
forward declaration of 
前置声明
request for
要求
which is of pointer type
但它是指针类型
maybe you meant to use
也许你想要使用
stray
非法字符
in program
在程序中
at end of input
在输入文件的末尾
missing terminating
缺失终止的 
expected
期待
expects
期待
initializer
初始化
unqualified-id
非限定标识
primary-expression
基本表达式
declaration
声明
identifier
标识符
token
符号
nested-name-specifier
嵌套名字说明符
before
在此之前:
failed
失败
constructor
构造函数
destructor
析构函数
type conversion
类型转换
operand
操作数
iteration
迭代
character
字符
operator
运算符
Information
信息
argument
参数
file
文件
function
函数
member
成员
forget
忘记
forward
前置
for
对于
from
从
 and 
 和 
 to 
 到 
 or 
 或 
